name: Release package

on:
  workflow_dispatch:

jobs:
  release:
    name: Release @pubnub/tomato
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build all packages
        run: npm run build
      - name: test
        run: cat ~/.npmrc
      - name: Release
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
