name: Release package

on:
  workflow_dispatch:

jobs:
  release:
    name: Release @pubnub/tomato
    runs-on:
      group: Default
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Update credentials
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > "$NPM_CONFIG_USERCONFIG"
      - name: Install dependencies
        run: npm ci
      - name: Build all packages
        run: npm run build
      - name: Test npm
        run: npm whoami
      - name: Release
        run: npm publish --access public
